service: 'serverless-postnl'
frameworkVersion: '3'
plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-offline-sqs
  
provider: 
  name: 'aws'
  region: 'eu-west-1'
  runtime: 'nodejs14.x'
  apiGateway: 
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  
  environment: 
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'

resources: 
  - ${file(./infra/sqs/gpsCoordinatesQueue.yml)}
  - ${file(./infra/sns/iotPlatformNotificationsTopic.yml)}
  - ${file(./infra/dynamodb/gpsCoordinatesTable.yml)}
  - ${file(./infra/dynamodb/vehicleToHandheldTable.yml)}

functions:
  - ${file(./src/functions/saveLocation/function.yml)}
  - ${file(./src/functions/checkHandheldVehicleDistance/function.yml)}

package:  
  individually: true 
custom: 
  esbuild: 
    bundle: true
    minify: false
    sourcemap: true
    exclude: 
    - 'aws-sdk'
    target: 'node14'
    platform: 'node'
    concurrency: 10

