Resources:
  VehicleToHandheldTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: VehicleToHandheldTable
      AttributeDefinitions:
        - AttributeName: vehicleMacAddress
          AttributeType: S
        - AttributeName: handheldMacAddress
          AttributeType: S
      KeySchema:
        - AttributeName: vehicleMacAddress
          KeyType: HASH
        - AttributeName: handheldMacAddress
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1